### ISSUE TITLE
please correct it

### ISSUE THREAD

**Issue by himanshukr17** [coding-blocks-archives/PythonAppDevMarch19_PP#1]
![Screen Shot 2019-03-11 at 4 20 48 PM](https://user-images.githubusercontent.com/48213505/54118791-df231400-4419-11e9-9912-10f2342b0c5d.png)

**Comment by nikhilkumarsingh** [comment]
Why have you given indentation in line no. 2?
And please use the whatsapp group for asking such kind of doubts.
